- name: Build And Deploy
  id: builddeploy
  uses: Azure/static-web-apps-deploy@v1
  with:
    azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WONDERFUL_BAY_08090C700 }}
    action: "upload"
    app_location: "/" # App source code path
    output_location: "/" # Built app content directory - optional
    app_build_command: "" # Explicitly skip the build step
    github_id_token: ${{ steps.idtoken.outputs.result }}
